# Generated by Django 5.2.3 on 2025-08-31 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('document_type', models.CharField(choices=[('text', 'Text Document'), ('pdf', 'PDF Document'), ('csv', 'CSV Document'), ('json', 'JSON Document'), ('other', 'Other')], default='text', max_length=10)),
                ('source_path', models.CharField(help_text='Path to the original document', max_length=500)),
                ('content_hash', models.CharField(help_text='SHA-256 hash of document content', max_length=64, unique=True)),
                ('chunk_count', models.PositiveIntegerField(default=0, help_text='Number of chunks created')),
                ('embedding_model', models.CharField(help_text='Embedding model used', max_length=100)),
                ('vector_store_id', models.CharField(help_text='ID in vector store', max_length=100)),
                ('retrieval_count', models.PositiveIntegerField(default=0, help_text='Number of times retrieved')),
                ('average_similarity_score', models.FloatField(default=0.0, help_text='Average similarity score when retrieved')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(default=dict, help_text='Additional document metadata')),
            ],
            options={
                'verbose_name': 'RAG Document',
                'verbose_name_plural': 'RAG Documents',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='RAGDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the dialogue', max_length=200)),
                ('dialogue_type', models.CharField(choices=[('general', 'General Query'), ('esg', 'ESG Analysis'), ('compliance', 'Compliance Check'), ('research', 'Research Query'), ('analysis', 'Data Analysis'), ('custom', 'Custom Topic')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('llm_provider', models.CharField(default='openai', help_text='LLM provider used', max_length=50)),
                ('llm_model', models.CharField(default='gpt-3.5-turbo', help_text='LLM model used', max_length=100)),
                ('vector_store_type', models.CharField(default='chroma', help_text='Vector store type', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_exchanges', models.PositiveIntegerField(default=0)),
                ('total_tokens_used', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_dialogues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG Dialogue',
                'verbose_name_plural': 'RAG Dialogues',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='RAGExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(help_text="The user's question")),
                ('system_response', models.TextField(help_text="The system's response")),
                ('processing_time', models.FloatField(default=0.0, help_text='Total processing time in seconds')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Total tokens used')),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, help_text='Cost of this exchange', max_digits=10)),
                ('retrieved_documents', models.JSONField(default=list, help_text='List of retrieved documents')),
                ('context_used', models.TextField(blank=True, help_text='Context provided to the LLM')),
                ('similarity_scores', models.JSONField(default=list, help_text='Similarity scores for retrieved documents')),
                ('retrieval_time', models.FloatField(default=0.0, help_text='Document retrieval time')),
                ('context_prep_time', models.FloatField(default=0.0, help_text='Context preparation time')),
                ('llm_processing_time', models.FloatField(default=0.0, help_text='LLM processing time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exchange_number', models.PositiveIntegerField(help_text='Order of this exchange in the dialogue')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='rag.ragdialogue')),
            ],
            options={
                'verbose_name': 'RAG Exchange',
                'verbose_name_plural': 'RAG Exchanges',
                'ordering': ['exchange_number'],
            },
        ),
        migrations.CreateModel(
            name='RAGSystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('log_type', models.CharField(choices=[('system', 'System'), ('user_action', 'User Action'), ('processing', 'Processing'), ('error', 'Error'), ('performance', 'Performance')], default='system', max_length=20)),
                ('message', models.TextField(help_text='Log message')),
                ('details', models.JSONField(default=dict, help_text='Additional log details')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('dialogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='rag.ragdialogue')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='rag.ragexchange')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG System Log',
                'verbose_name_plural': 'RAG System Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
