# Generated by Django 5.2.3 on 2025-09-14 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Question title or form name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description or instructions')),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('email', 'Email'), ('number', 'Number'), ('select', 'Select Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('datetime', 'Date and Time')], default='text', max_length=20)),
                ('field_name', models.CharField(help_text='Internal field name for JSON storage', max_length=100)),
                ('field_label', models.CharField(help_text='Display label for the field', max_length=200)),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text', max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/radio/checkbox fields')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Custom validation rules')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.CharField(max_length=200)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
