# Generated by Django 5.2.3 on 2025-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_two_factor_enabled_profile_two_factor_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recovery_codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
