# Generated by Django 5.2.3 on 2025-09-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subscriptionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_country',
            field=models.CharField(blank=True, help_text="User's country", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, help_text="User's timezone (e.g., 'Europe/Copenhagen')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_preference',
            field=models.CharField(blank=True, help_text="User's preferred language code (e.g., 'en', 'da')", max_length=10, null=True),
        ),
    ]
